
/* Drop Tables */

DROP TABLE IF EXISTS RESULT_DETAIL;
DROP TABLE IF EXISTS ANALYSIS_RESULT;
DROP TABLE IF EXISTS ANALYSIS;
DROP TABLE IF EXISTS CODE;
DROP TABLE IF EXISTS CONDITION_DETAIL;
DROP TABLE IF EXISTS CONDITION;
DROP TABLE IF EXISTS POI;
DROP TABLE IF EXISTS REAL_ESTATE;
DROP TABLE IF EXISTS SAFETY;
DROP TABLE IF EXISTS SEARCH_HISTORY;




/* Create Tables */

CREATE TABLE ANALYSIS
(
	ANAL_SN varchar(10) NOT NULL,
	CON_SN varchar(10) NOT NULL,
	ANAL_DATE date,
	ANAL_SCRAP char(1),
	ANAL_DELETE_DATE date,
	PRIMARY KEY (ANAL_SN)
) WITHOUT OIDS;


CREATE TABLE ANALYSIS_RESULT
(
	ANAL_SN varchar(10) NOT NULL,
	RESULT_NO numeric NOT NULL,
	SHAPE_LENG numeric,
	SHAPE_AREA numeric,
	GEOM bigint,
	PRIMARY KEY (ANAL_SN, RESULT_NO)
) WITHOUT OIDS;


CREATE TABLE CODE
(
	CODE varchar(10) NOT NULL,
	CODE_NM varchar(10),
	CODE_PRE varchar(10),
	PRIMARY KEY (CODE)
) WITHOUT OIDS;


CREATE TABLE CONDITION
(
	CON_SN varchar(10) NOT NULL,
	CON_NM varchar(300),
	CON_RANGE numeric,
	CON_DATE date,
	-- 읍면동 단위
	CON_AREA varchar(100),
	CON_DELETE_DATE date,
	PRIMARY KEY (CON_SN)
) WITHOUT OIDS;


CREATE TABLE CONDITION_DETAIL
(
	CON_SN varchar(10) NOT NULL,
	CD_CODE varchar(10) NOT NULL,
	CD_DATE date,
	CD_DELETE_DATE date,
	PRIMARY KEY (CON_SN, CD_CODE)
) WITHOUT OIDS;


CREATE TABLE POI
(
	POI_NO varchar(10) NOT NULL,
	POI_CODE varchar(10),
	POI_NM varchar(300),
	POI_ADDR varchar(1000),
	POI_PNU varchar(19),
	POI_LONG varchar(50),
	POI_LAT varchar(50),
	POI_X varchar(50),
	POI_Y varchar(50),
	POI_GEOM bigint,
	PRIMARY KEY (POI_NO)
) WITHOUT OIDS;


CREATE TABLE REAL_ESTATE
(
	RS_NO varchar(10) NOT NULL,
	TYPE_CODE varchar(10),
	SGG varchar(300),
	BEONJI varchar(10),
	DANJI varchar(300),
	LEASE_CODE numeric,
	AREA numeric,
	CONTRACT_YM varchar(6),
	CONTRACT_D varchar(2),
	DEPOSIT numeric,
	RENT numeric,
	FLOOR numeric,
	BUILT_DATE date,
	STREET_NM varchar(300),
	CONTRACT_PERIOD varchar(19),
	CONTRACT_CODE varchar(10),
	PRIMARY KEY (RS_NO)
) WITHOUT OIDS;


CREATE TABLE RESULT_DETAIL
(
	ANAL_SN varchar(10) NOT NULL,
	RESULT_NO numeric NOT NULL,
	-- 첨부파일 같이
	EACH_PK varchar(10)
) WITHOUT OIDS;


CREATE TABLE SAFETY
(
	SAFETY_NO varchar(10) NOT NULL,
	SAFETY_CODE varchar(10),
	SAFETY_NM varchar(300),
	SAFETY_ADDR varchar(1000),
	SAFETY_PNU varchar(19),
	SAFETY_LONG varchar(50),
	SAFETY_LAT varchar(50),
	SAFETY_X varchar(50),
	SAFETY_Y varchar(50),
	SAFETY_GEOM bigint,
	PRIMARY KEY (SAFETY_NO)
) WITHOUT OIDS;


CREATE TABLE SEARCH_HISTORY
(
	SH_NO varchar(10) NOT NULL,
	SEARCH_NM varchar(300),
	SEARCH_DATE date,
	SEARCH_DELETE_DATE date,
	PRIMARY KEY (SH_NO)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE ANALYSIS_RESULT
	ADD FOREIGN KEY (ANAL_SN)
	REFERENCES ANALYSIS (ANAL_SN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RESULT_DETAIL
	ADD FOREIGN KEY (ANAL_SN, RESULT_NO)
	REFERENCES ANALYSIS_RESULT (ANAL_SN, RESULT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ANALYSIS
	ADD FOREIGN KEY (CON_SN)
	REFERENCES CONDITION (CON_SN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONDITION_DETAIL
	ADD FOREIGN KEY (CON_SN)
	REFERENCES CONDITION (CON_SN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN CONDITION.CON_AREA IS '읍면동 단위';
COMMENT ON COLUMN RESULT_DETAIL.EACH_PK IS '첨부파일 같이';



